### PR TITLE
Store/compare with encrypted passwords

### PR DESCRIPTION
**Pull request by psybuzz**
This PR makes new changes to the way that passwords are stored on user creation as well as how passwords are compared when logging in.  Such changes use the Bcrypt node module to bring an added level of security that should likely be expected of any publicly facing webapp.

After password encryption, we will no longer be storing plaintext passwords in our database, which means that we will not be able to view any user's real password.  From an ethical perspective, this implies that, given an official request to reveal our users' passwords, we will be technically unable to do so.

From a technical perspective, any accounts that were created prior to this PR will be unable to login.  As such, we can either:
- Wipe the Mongo database and start fresh with new accounts
- Write a script to hash all existing passwords

### CODE REVIEW

**Comment by tonyxj** [comment]
It's a bummer to wipe the app clean, but on the other hand it does make things a lot easier. I think having a copy of the conversations is a good way to go! Since @psybuzz has already sent us the copy, I think we can go ahead with giving it a fresh start.

**Comment by psybuzz** [comment]
Alright, I'm about to clear the DB and merge this in.  I'll let you both know how it ends up.

**Comment by psybuzz** [comment]
Okay, the DB has been wiped, and this branch is merged.  I've run it locally once more, and things seem functional.

OK: User creation, convo creation, email notifications, posting to a convo.

I will now attempt to push to Heroku

**Comment by psybuzz** [comment]
Alright!  The changes are live on Heroku, it seems to still be completely functional.

OK: User creation, convo creation, email notifications, posting to a convo, leaving a convo, created a fake account, global search for other users, adding other users to a convo.

And if you log into the DB, you won't find any plaintext passwords!  Yay!

**Comment by tonyxj** [comment]
Das ist fantastisch! :+1:

**Pull request merged**
